"use client";

import { motion } from "framer-motion";

export default function GeneratedBySlide() {
  return (
    <div className="slide-content">
      <motion.div 
        className="generated-slide"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.4 }}
      >
        <motion.h1
          className="font-sans font-bold text-4xl md:text-6xl mb-3 animate-in slide-in-from-bottom-10 duration-500 ease-out tracking-[-3px] text-balance"
          initial={{ y: -20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.1, duration: 0.3 }}
        >
          Generated by <span className="font-serif italic font-normal tracking-[-1.8px]">Macaly</span>
        </motion.h1>
        <motion.p
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.2, duration: 0.3 }}
        >
          This entire presentation, including all slides, design, and content, 
          was generated and designed by Macaly.
        </motion.p>
      </motion.div>
    </div>
  );
}